pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    set -e
    /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
    disown -ar
  displayName: 'Start xvfb'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'java-design-patterns'
    organization: 'willsmythe-github'
    scannerMode: Other

- task: Maven@3
  inputs:
    options: '-Dsonar.projectKey=java-design-patterns'
    mavenPomFile: 'pom.xml'
    mavenOpts: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    sonarQubeRunAnalysis: true
    goals: 'test'
